// AUTO-GENERATED by scripts/sync-aesthetic-videos.mjs — do not edit by hand.
export interface AestheticVideo {
  id: string;
  name: string;
  file: string;
  /** Duration in whole seconds, probed at sync time (null if unknown). */
  duration: number | null;
}

export const AESTHETIC_VIDEOS: AestheticVideo[] = [
  {
    "id": "aesthetic-1",
    "name": "Aesthetic 1",
    "file": "/videos/aesthetic/aesthetic-1.mp4",
    "duration": 60
  },
  {
    "id": "aesthetic-2",
    "name": "Aesthetic 2",
    "file": "/videos/aesthetic/aesthetic-2.mp4",
    "duration": 12
  }
];
