import { Reciter } from "@/types";

export const reciters: Reciter[] = [
  { id: "alafasy", name: "Mishary Rashid Alafasy", folder: "Alafasy_128kbps" },
  { id: "sudais", name: "Abdul Rahman Al-Sudais", folder: "Abdurrahmaan_As-Sudais_192kbps" },
  { id: "muaiqly", name: "Maher Al-Muaiqly", folder: "MaherAlMuaiqly128kbps" },
  { id: "dussary", name: "Yasser Ad-Dussary", folder: "Yasser_Ad-Dussary_128kbps" },
  { id: "ghamdi", name: "Saad Al-Ghamdi", folder: "Ghamadi_40kbps" },
  { id: "husary", name: "Mahmoud Khalil Al-Husary", folder: "Husary_128kbps" },
  { id: "basit-murattal", name: "Abdul Basit (Murattal)", folder: "Abdul_Basit_Murattal_192kbps" },
  { id: "basit-mujawwad", name: "Abdul Basit (Mujawwad)", folder: "Abdul_Basit_Mujawwad_128kbps" },
  { id: "shuraym", name: "Saud Ash-Shuraym", folder: "Saood_ash-Shuraym_128kbps" },
  { id: "shaatree", name: "Abu Bakr Ash-Shaatree", folder: "Abu_Bakr_Ash-Shaatree_128kbps" },
  { id: "qatami", name: "Nasser Al-Qatami", folder: "Nasser_Alqatami_128kbps" },
  { id: "ajmy", name: "Ahmed Al-Ajmy", folder: "ahmed_ibn_ali_al_ajamy_128kbps" },
  { id: "rifai", name: "Hani Ar-Rifai", folder: "Hani_Rifai_192kbps" },
  { id: "baleela", name: "Bandar Baleela", folder: "Bandar_Balila_128kbps" },
  { id: "luhaidan", name: "Muhammad Al-Luhaidan", folder: "Muhammad_Al-Luhaidan_128kbps" },
  { id: "abbad", name: "Fares Abbad", folder: "Fares_Abbad_64kbps" },
  { id: "minshawi-murattal", name: "Muhammad Al-Minshawi (Murattal)", folder: "Minshawi_Murattal_128kbps" },
  { id: "minshawi-mujawwad", name: "Muhammad Al-Minshawi (Mujawwad)", folder: "Minshawy_Mujawwad_192kbps" },
  { id: "tablawy", name: "Muhammad Al-Tablawi", folder: "Mohammad_al_Tablaway_128kbps" },
  { id: "jaber", name: "Ali Jaber", folder: "Ali_Jaber_64kbps" },
  { id: "idrees", name: "Idris Abkar", folder: "Idrees_Abkar_128kbps" },
  { id: "qahtani", name: "Khalid Al-Qahtani", folder: "Khalid_AlQahtani_128kbps" },
  { id: "ayyub", name: "Muhammad Ayyub", folder: "Muhammad_Ayyoub_128kbps" },
  { id: "hudhaify", name: "Ali Al-Hudhaify", folder: "Hudhaify_128kbps" },
  { id: "juhainy", name: "Abdullah Al-Juhany", folder: "Abdullaah_3awwaad_Al-Juhaynee_128kbps" },
];
