import { StyleSettings } from "./style";

export interface Template {
  id: string;
  name: string;
  /** Small CSS background used for the template's swatch in the picker. */
  swatch: string;
  settings: StyleSettings;
}

const baseShadow = { enabled: true, color: "#000000", blur: 6, offsetX: 0, offsetY: 2 };
const noLetterbox = { enabled: false, barColor: "#000000", barStyle: "solid" as const };

export const TEMPLATES: Template[] = [
  {
    id: "arabic-focus",
    name: "Arabic Focus",
    swatch: "linear-gradient(180deg, #050507 0%, #16213e 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 38,
      arabicFontWeight: 400,
      arabicEnabled: true,
      lineHeight: 1.08,
      textPosition: 50,
      textLayout: "center",
      translationEnabled: false,
      translationFont: "sans-serif",
      translationFontSize: 14,
      translationFontWeight: 500,
      textColor: "#ffffff",
      overlayOpacity: 18,
      overlayColor: "#000000",
      textShadow: { enabled: true, color: "#000000", blur: 10, offsetX: 0, offsetY: 2 },
      highlightEnabled: true,
      highlightColor: "#050507",
      highlightOpacity: 0.82,
      highlightRadius: 0.18,
      highlightPadding: 0.65,
      highlightHeight: 1,
      background: { type: "solid", value: "#08090d", label: "Upload B-roll" },
      backgroundFit: "cover",
      verseIntro: "fade",
      verseIntroMs: 280,
      letterbox: noLetterbox,
    },
  },
  {
    id: "translation-focus",
    name: "Translation Focus",
    swatch: "#08090d",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 30,
      arabicFontWeight: 400,
      arabicEnabled: false,
      lineHeight: 1,
      textPosition: 50,
      textLayout: "center",
      translationEnabled: true,
      translationFont: "sans-serif",
      translationFontSize: 24,
      translationFontWeight: 700,
      textColor: "#ffffff",
      overlayOpacity: 50,
      overlayColor: "#000000",
      textShadow: { enabled: true, color: "#000000", blur: 12, offsetX: 0, offsetY: 2 },
      background: { type: "solid", value: "#08090d", label: "Black" },
      backgroundFit: "cover",
      verseIntro: "fade",
      verseIntroMs: 260,
      letterbox: noLetterbox,
    },
  },
  {
    id: "reciter-split",
    name: "Reciter Split",
    swatch: "linear-gradient(90deg, #050507 0%, #050507 48%, #26354a 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 27,
      arabicFontWeight: 400,
      lineHeight: 1.08,
      translationLineHeight: 1.12,
      arabicTranslationGap: 0.72,
      textPosition: 48,
      textLayout: "left-panel",
      translationEnabled: true,
      translationFont: "sans-serif",
      translationFontSize: 13,
      translationFontWeight: 600,
      textColor: "#f4f1e8",
      overlayOpacity: 8,
      overlayColor: "#050507",
      textShadow: { enabled: true, color: "#050507", blur: 5, offsetX: 0, offsetY: 1 },
      background: { type: "solid", value: "#08090d", label: "Reciter video" },
      backgroundFit: "cover",
      verseIntro: "fade",
      verseIntroMs: 320,
      letterbox: noLetterbox,
    },
  },
  {
    id: "midnight-gold",
    name: "Midnight Gold",
    swatch: "linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 34,
      arabicFontWeight: 400,
      lineHeight: 1.1,
      textPosition: 46,
      translationEnabled: true,
      translationFont: "playfair-display",
      translationFontSize: 15,
      translationFontWeight: 400,
      textColor: "#f3ecd9",
      overlayOpacity: 35,
      overlayColor: "#000000",
      textShadow: { enabled: true, color: "#000000", blur: 8, offsetX: 0, offsetY: 2 },
      background: { type: "gradient", value: "linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)", label: "Night Sky" },
      letterbox: noLetterbox,
    },
  },
  {
    id: "pure-minimal",
    name: "Pure Minimal",
    swatch: "#0a0a0a",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 30,
      arabicFontWeight: 400,
      lineHeight: 1,
      textPosition: 50,
      translationEnabled: true,
      translationFont: "sans-serif",
      translationFontSize: 14,
      translationFontWeight: 400,
      textColor: "#ffffff",
      overlayOpacity: 0,
      overlayColor: "#000000",
      textShadow: { enabled: false, color: "#000000", blur: 0, offsetX: 0, offsetY: 0 },
      background: { type: "solid", value: "#0a0a0a", label: "Black" },
      letterbox: noLetterbox,
    },
  },
  {
    id: "emerald-calm",
    name: "Emerald Calm",
    swatch: "linear-gradient(135deg, #0a3d0a 0%, #0a0a0a 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 32,
      arabicFontWeight: 400,
      lineHeight: 1.05,
      textPosition: 48,
      translationEnabled: true,
      translationFont: "lora",
      translationFontSize: 14,
      translationFontWeight: 400,
      textColor: "#eaf3ea",
      overlayOpacity: 30,
      overlayColor: "#04130a",
      textShadow: baseShadow,
      background: { type: "gradient", value: "linear-gradient(135deg, #0a3d0a 0%, #0a0a0a 100%)", label: "Forest Dark" },
      letterbox: noLetterbox,
    },
  },
  {
    id: "deep-ocean",
    name: "Deep Ocean",
    swatch: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 32,
      arabicFontWeight: 400,
      lineHeight: 1.05,
      textPosition: 48,
      translationEnabled: true,
      translationFont: "lora",
      translationFontSize: 14,
      translationFontWeight: 400,
      textColor: "#eef3fb",
      overlayOpacity: 25,
      overlayColor: "#000814",
      textShadow: baseShadow,
      background: { type: "gradient", value: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)", label: "Deep Ocean" },
      letterbox: noLetterbox,
    },
  },
  {
    id: "warm-sepia",
    name: "Warm Sepia",
    swatch: "linear-gradient(135deg, #1a0a0a 0%, #3d1a1a 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 33,
      arabicFontWeight: 400,
      lineHeight: 1.05,
      textPosition: 48,
      translationEnabled: true,
      translationFont: "playfair-display",
      translationFontSize: 14,
      translationFontWeight: 400,
      textColor: "#f5e8d6",
      overlayOpacity: 28,
      overlayColor: "#1a0a0a",
      textShadow: baseShadow,
      background: { type: "gradient", value: "linear-gradient(135deg, #1a0a0a 0%, #3d1a1a 100%)", label: "Warm Dark" },
      letterbox: noLetterbox,
    },
  },
  {
    id: "cinematic",
    name: "Cinematic",
    swatch: "linear-gradient(180deg, #000 0%, #111 50%, #000 100%)",
    settings: {
      arabicFont: "uthmanic-hafs",
      arabicFontSize: 30,
      arabicFontWeight: 400,
      lineHeight: 1,
      textPosition: 50,
      translationEnabled: true,
      translationFont: "cinzel",
      translationFontSize: 13,
      translationFontWeight: 400,
      textColor: "#ffffff",
      overlayOpacity: 35,
      overlayColor: "#000000",
      textShadow: baseShadow,
      background: { type: "solid", value: "#0a0a0a", label: "Black" },
      letterbox: { enabled: true, barColor: "#000000", barStyle: "solid" },
    },
  },
];
