import type { StyleSettings } from "./style";
import type { TemplateDefinition } from "./template-model";
import { DEFAULT_SPLIT_MASK } from "./canvas-utils";

const noLetterbox = {
  enabled: false,
  barColor: "#000000",
  barStyle: "solid" as const,
};

const base: StyleSettings = {
  arabicFont: "qcf",
  arabicFontSize: 30,
  arabicFontWeight: 400,
  arabicInkThickness: 0.75,
  arabicEnabled: true,
  arabicVerseNumber: false,
  translationVerseNumber: false,
  lineHeight: 1.05,
  translationLineHeight: 1.18,
  arabicTranslationGap: 0.62,
  textPosition: 50,
  textLayout: "center",
  splitMask: { ...DEFAULT_SPLIT_MASK },
  translationEnabled: true,
  translationFont: "lora",
  translationFontSize: 14,
  translationFontWeight: 500,
  textColor: "#f5f2e9",
  translationColor: "#d8d3c7",
  overlayOpacity: 42,
  overlayColor: "#000000",
  textShadow: {
    enabled: true,
    color: "#000000",
    blur: 7,
    offsetX: 0,
    offsetY: 2,
  },
  textOutline: {
    enabled: true,
    color: "#050507",
    width: 1.25,
  },
  highlightEnabled: false,
  highlightColor: "#74652d",
  highlightOpacity: 0.76,
  highlightRadius: 0.16,
  highlightPadding: 0.48,
  highlightHeight: 0.56,
  background: {
    type: "gradient",
    value: "linear-gradient(160deg, #111319 0%, #050507 100%)",
    label: "Midnight",
  },
  backgroundFit: "cover",
  fitBackdrop: "black",
  mediaTransform: { scale: 1, x: 0, y: 0 },
  mediaFrame: { shape: "full", x: 50, y: 50, width: 100, height: 100, radius: 6 },
  videoLoopMode: "loop",
  verseIntro: "fade",
  verseIntroMs: 320,
  letterbox: noLetterbox,
};

export const DEFAULT_TEMPLATE_STYLE: StyleSettings = {
  ...base,
  textShadow: { ...base.textShadow },
  textOutline: { ...base.textOutline! },
  background: { ...base.background },
  letterbox: { ...base.letterbox },
  mediaTransform: { ...base.mediaTransform! },
  mediaFrame: { ...base.mediaFrame! },
  splitMask: { ...base.splitMask! },
};

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: "ayahclip-gold-line",
    source: "built-in",
    name: "AyahClip Gold Line",
    description: "The signature dark reciter look from @ayahclip, with a warm active-line marker.",
    family: "ayahclip",
    featured: true,
    swatch: "linear-gradient(160deg, #111319 0%, #050507 100%)",
    mediaPolicy: "preserve-current-media",
    settings: {
      ...base,
      arabicFontSize: 32,
      textPosition: 53,
      translationFont: "lora",
      translationFontSize: 14,
      translationFontWeight: 500,
      overlayOpacity: 52,
      highlightEnabled: true,
      highlightColor: "#74652d",
      highlightOpacity: 0.72,
      highlightRadius: 0.12,
      highlightPadding: 0.5,
      highlightHeight: 0.52,
      backgroundFit: "contain",
      fitBackdrop: "black",
    },
    extras: {
      clipFadeMs: 380,
      safeAreaTarget: "tiktok",
      safePadding: 0,
    },
    mediaSlots: [
      { id: "background", accepts: "video", label: "Add reciter or archival video" },
    ],
  },
  {
    id: "reciter-split-fade",
    source: "built-in",
    name: "Reciter Split Fade",
    description: "Black reading panel on the left, fading into the reciter on the right.",
    family: "reciter",
    featured: true,
    swatch: "linear-gradient(90deg, #050507 0%, #050507 48%, #26354a 100%)",
    mediaPolicy: "preserve-current-media",
    settings: {
      ...base,
      // A real Bold Naskh face keeps the traditional Quranic silhouette while
      // remaining legible over short-form video.
      arabicFont: "scheherazade-new",
      arabicFontWeight: 700,
      arabicInkThickness: 0,
      // Scheherazade is wider than Noto Naskh; this compact scale keeps the real Short sample
      // to two lines in the 50% reading panel without thinning the face.
      arabicFontSize: 30,
      lineHeight: 1.08,
      textPosition: 49,
      textLayout: "left-panel",
      splitMask: {
        side: "left",
        color: "#050507",
        opacity: 1,
        solidWidth: 50,
        fadeWidth: 20,
      },
      translationFont: "outfit",
      translationFontSize: 14,
      translationFontWeight: 600,
      textColor: "#f4f1e8",
      translationColor: "#d7d2c6",
      overlayOpacity: 10,
      background: {
        type: "gradient",
        value: "linear-gradient(90deg, #050507 0%, #050507 48%, #26354a 100%)",
        label: "Add reciter video",
      },
      textShadow: { enabled: true, color: "#050507", blur: 5, offsetX: 0, offsetY: 1 },
      textOutline: { enabled: true, color: "#050507", width: 1.5 },
    },
    extras: {
      clipFadeMs: 320,
      safeAreaTarget: "tiktok",
      safePadding: 0,
    },
    mediaSlots: [
      { id: "background", accepts: "video", label: "Add reciter video" },
    ],
  },
  {
    id: "nature-reflection",
    source: "built-in",
    name: "Nature Reflection",
    description: "Full-height nature B-roll with a restrained white glow and literary translation.",
    family: "nature",
    featured: true,
    swatch: "linear-gradient(155deg, #10241b 0%, #050907 100%)",
    mediaPolicy: "preserve-current-media",
    settings: {
      ...base,
      arabicFontSize: 32,
      textPosition: 49,
      translationFont: "lora",
      translationFontSize: 14,
      translationFontWeight: 500,
      overlayOpacity: 48,
      overlayColor: "#030806",
      textShadow: { enabled: true, color: "#f7f3e8", blur: 5, offsetX: 0, offsetY: 0 },
      textOutline: { enabled: true, color: "#040806", width: 1 },
      background: {
        type: "gradient",
        value: "linear-gradient(155deg, #10241b 0%, #050907 100%)",
        label: "Add nature B-roll",
      },
    },
    extras: {
      clipFadeMs: 420,
      safeAreaTarget: "tiktok",
      safePadding: 0,
    },
    mediaSlots: [
      { id: "background", accepts: "image-or-video", label: "Add nature B-roll" },
    ],
  },
  {
    id: "clean-ink",
    source: "built-in",
    name: "Clean Ink",
    description: "Pure black, crisp Quran text, and no unnecessary decoration.",
    family: "minimal",
    featured: true,
    swatch: "#050507",
    mediaPolicy: "use-template-media",
    settings: {
      ...base,
      arabicFontSize: 30,
      translationFont: "outfit",
      translationFontSize: 14,
      translationFontWeight: 500,
      overlayOpacity: 0,
      textShadow: { enabled: true, color: "#000000", blur: 2, offsetX: 0, offsetY: 1 },
      verseIntro: "none",
      background: { type: "solid", value: "#050507", label: "Ink" },
    },
    extras: {
      clipFadeMs: 0,
      safeAreaTarget: "tiktok",
      safePadding: 0,
      backgroundSequence: {
        enabled: false,
        sceneCount: 1,
        duration: 5,
        transition: "cut",
        transitionDuration: 0.1,
      },
    },
    mediaSlots: [],
  },
  {
    id: "translation-led",
    source: "built-in",
    name: "Translation Led",
    description: "Large, readable English with smaller Arabic retained for Quran context.",
    family: "minimal",
    featured: false,
    swatch: "linear-gradient(180deg, #0c1017 0%, #050507 100%)",
    mediaPolicy: "use-template-media",
    settings: {
      ...base,
      arabicFontSize: 29,
      lineHeight: 1,
      arabicTranslationGap: 0.95,
      translationFont: "outfit",
      translationFontSize: 19,
      translationFontWeight: 700,
      translationLineHeight: 1.12,
      overlayOpacity: 0,
      background: {
        type: "gradient",
        value: "linear-gradient(180deg, #0c1017 0%, #050507 100%)",
        label: "Deep ink",
      },
    },
    extras: {
      clipFadeMs: 240,
      safeAreaTarget: "tiktok",
      safePadding: 0,
      backgroundSequence: {
        enabled: false,
        sceneCount: 1,
        duration: 5,
        transition: "cut",
        transitionDuration: 0.1,
      },
    },
    mediaSlots: [],
  },
  {
    id: "broll-rotation",
    source: "built-in",
    name: "B-roll Rotation",
    description: "Three visual slots with slow crossfades while the caption treatment stays consistent.",
    family: "broll",
    featured: true,
    swatch: "linear-gradient(135deg, #12201a 0%, #101827 50%, #1e1510 100%)",
    mediaPolicy: "preserve-current-media",
    settings: {
      ...base,
      arabicFontSize: 30,
      translationFont: "lora",
      translationFontSize: 14,
      overlayOpacity: 54,
      textShadow: { enabled: true, color: "#000000", blur: 9, offsetX: 0, offsetY: 2 },
      background: {
        type: "gradient",
        value: "linear-gradient(135deg, #12201a 0%, #101827 50%, #1e1510 100%)",
        label: "Add B-roll",
      },
    },
    extras: {
      clipFadeMs: 400,
      safeAreaTarget: "tiktok",
      safePadding: 0,
      backgroundSequence: {
        enabled: true,
        sceneCount: 3,
        duration: 5,
        transition: "crossfade",
        transitionDuration: 0.6,
      },
    },
    mediaSlots: [
      { id: "scene:0", accepts: "image-or-video", label: "B-roll 1" },
      { id: "scene:1", accepts: "image-or-video", label: "B-roll 2" },
      { id: "scene:2", accepts: "image-or-video", label: "B-roll 3" },
    ],
  },
];

export function getBuiltInTemplate(id: string): TemplateDefinition | undefined {
  return TEMPLATES.find((template) => template.id === id);
}
